name: Continuous Deployment Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/EChat.Frontend/**"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Run custom environment configuration
        run: node src/EChat.Frontend/custom-environment.config.js
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          CHAT_HUB: ${{ secrets.CHAT_HUB }}

      - name: Build and Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/EChat.Frontend"
          output_location: "dist/browser"
        env:
          NPM_CONFIG_FORCE: true
